version: '3.8'
services:
  app:
    image: mooflowai/moof-mcp:p4aacnr9zhke
    container_name: app
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
    environment: {}
    restart: always
    ports:
      - '5555:3000'
